### ISSUE TITLE
St7789 Esp 8266 Adafruit Ошибка #include <util/delay.h>

### ISSUE THREAD

**Issue by Muhammedjan** [adafruit/Adafruit_VEML6075#11]
Hi all. I've been looking for an answer to this error for a day now. Tried loading other libraries. Perekstonovil libraries but did not find a positive result. In arduino nano everything is loaded and in esp 8266 nodemcu there is such an error. If you help I will be glad
full error name:
Arduino: 1.8.19 (Windows 7), Плата:"NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, Disabled (new aborts on oom), Disabled, All SSL ciphers (most compatible), 32KB cache + 32KB IRAM (balanced), Use pgm_read macros for IRAM/PROGMEM, 4MB (FS:2MB OTA:~1019KB), 2, v2 Lower Memory, Disabled, None, Only Sketch, 115200"

C:\Program Files (x86)\Arduino\libraries\Adafruit_GFX\Adafruit_PCD8544.cpp:26:10: fatal error: util/delay.h: No such file or directory

   26 | #include <util/delay.h>

      |          ^~~~~~~~~~~~~~

compilation terminated.

exit status 1

Ошибка компиляции для платы NodeMCU 1.0 (ESP-12E Module).

Неверная библиотека найдена в C:\Program Files (x86)\Arduino\libraries\DFPlayer-Mini-mp3-master: нет заголовочных файлов (.h), найденных в C:\Program Files (x86)\Arduino\libraries\DFPlayer-Mini-mp3-master

Возникла ошибка при загрузке https://downloads.arduino.cc/packages/package_index.json

Этот отчёт будет иметь больше информации с
включенной опцией Файл -> Настройки ->
"Показать подробный вывод во время компиляции"

**Comment by caternuson** [comment]
This is the Arduino library for the VEML6075 UV sensor:
https://www.adafruit.com/product/3964

The ST7789 is a TFT display driver.

The PCD8544 is a LCD display. The current library is not located within the Adafruit GFX library. It is here:
https://github.com/adafruit/Adafruit-PCD8544-Nokia-5110-LCD-library
and does not have the code line in your error message (no #include <util/delay.h>)

The second error message is indicating an issue with your Arduino IDE setup specific to the DFPlayer-Mini-mp3-master library.

It is very confusing what is being attempted here. Are you following a guide?

**Comment by ladyada** [comment]
you've messed up your library installation process. you should delete your libraries and re-install using the library manager. alsu use the latest arduino
