### ISSUE TITLE
can't verify the arduino 

### ISSUE THREAD

**Issue by Mayaadilla97** [adafruit/Adafruit_VEML6075#12]
i already install adafruit and everything 
but my arduino software can't verify the coding well 
![ERROR AFTER INSTALL busIO](https://user-images.githubusercontent.com/104315054/164985215-41974d11-a05f-4adc-aa9a-ef4137fac5ab.PNG)
can somebody guide me for the problem ?

**Comment by ladyada** [comment]
https://learn.adafruit.com/adafruit-veml6075-uva-uvb-uv-index-sensor/arduino-test

**Comment by Mayaadilla97** [comment]
[image: image.png]
when i follow link that you give i get this error . did you know why?
