### ISSUE TITLE
SAMD Incompatible with VEML6075

### ISSUE THREAD

**Issue by aemondis** [adafruit/Adafruit_VEML6075#3]
Similar to the referenced ESP32 Incompatibility concern, I believe the SAMD architecture (in my case, the MKR1000 and MKR1010 which are using CortexM0+ MCUs) has a similar issue with the I2C repeated start.

Whilst the VEML6075 works perfectly on a regular AVR Arduino Duo, with the exact same code and setup on the MKR platform; it does not even begin (and in actuality, the Adafruit example freezes the MKR platform as you are trying to read the UV levels when the Begin function returned "False", thus was not initialised).

I have tried the sample libraries as per the ESP32 issue - but no luck with either on the MKR.

**Comment by ladyada** [comment]
i belive this is fixed in latest commit, but you'll have to manually install BusIO library which we will be using
https://github.com/adafruit/Adafruit_BusIO
if it still doesnt work, plz reopen issue
