### ISSUE TITLE
Sleep mode is missing (to improve power consumption)

### ISSUE THREAD

**Issue by bonjour81** [adafruit/Adafruit_VEML6075#4]
Hi!
VEML6076 offers a shutdown mode to reduce power consumption (very important for battery operated setups).
According to datasheet, it seems to be a simple flag 'SD' to swith on or off to enter or exit sleep mode.

Would it be possible to add this feature ?

**Comment by ladyada** [comment]
please submit a PR and we'll check it :)

**Comment by manutremo** [comment]
Hi,

Looking through the code, I see a shutdown function which apparently does write to the sd register to get the chip on and off. Is that what you are referring to, or have I misunderstood?

**Comment by bonjour81** [comment]
oh...that's it, how could I missed it :(
Sorry for disturbance!!
