### ISSUE TITLE
Since version 2.0.0 "Adafruit_I2CDevice.h" is missing

### ISSUE THREAD

**Issue by gon0** [adafruit/Adafruit_VEML6075#5]
Just a hint, maybe it is not a real issue:

When installing version 2.0.0, I get this error:

```
C:\Users\xxxx\Documents\Arduino\libraries\Adafruit_VEML6075_Library/Adafruit_VEML6075.h:22:32: fatal error: Adafruit_I2CDevice.h: No such file or directory

 #include <Adafruit_I2CDevice.h>
```

When I revert back to version 1.0.0, everything compiles fine.

**Comment by ladyada** [comment]
follow https://learn.adafruit.com/adafruit-veml6075-uva-uvb-uv-index-sensor/arduino-test#install-arduino-libraries-4-4

**Comment by gon0** [comment]
This did the trick. Thanks!

**Comment by DanielB-1** [comment]
Having the same problem.
Not sure what the trick was ...

**Comment by peterfalk123** [comment]
Same problem here...solved it with installing the **Adafruit BusIO library** !

**Comment by DanielB-1** [comment]
Yes, found the same solution on a different forum. Worked fine after installing Adafruit BusIO library.

**Comment by kaybeebee** [comment]
> 
> 
> Same problem here...solved it with installing the **Adafruit BusIO library** !

Thanks! Helped fast.

**Comment by juanpabirsa** [comment]
> Same problem here...solved it with installing the **Adafruit BusIO library** !

Love u buddy. I've been dealing with that problem for like 2 hours and it solved my problem. THANK YOU VERY MUCH

**Comment by caternuson** [comment]
Adafruit BusIO library is listed as a dependency for this library: 
https://github.com/adafruit/Adafruit_VEML6075/blob/f655e28f362858b2aa2d232941f582ba2f77d1dc/library.properties#L10
It should be installed automatically if using latest version of Arduino IDE and Library Manager.

**Comment by MFahad7** [comment]
> Same problem here...solved it with installing the **Adafruit BusIO library** !

Thanks a lot
This helped

**Comment by sohaibqamar** [comment]
Thanks a bundle.

**Comment by diegodelaFuenteCuraqueo** [comment]
it works! after importing Adafruit BusIO library the error is gone... now I can play with my OLED screen

**Comment by bensnajder7** [comment]
I copy/paste it and still getting the same error. Can someone explain to me how did you install Adafruit BusIO library?

**Comment by amjed-ali-k** [comment]
> Same problem here...solved it with installing the **Adafruit BusIO library** !

Thanks a lot
