### ISSUE TITLE
VEML6075 EOL

### ISSUE THREAD

**Issue by szerwi** [adafruit/Adafruit_VEML6075#8]
As far as I know, VEML6075 is stated as end-of-life sensor since December 2019. Currently it is hard to get one on the online stores. Are there any alternatives for the VEML6075?

**Comment by ladyada** [comment]
only https://www.adafruit.com/product/4831

**Comment by szerwi** [comment]
@ladyada Unfortunately, this sensor does not give the UV index reading. So there is no alternative that outputs the UV index?

**Comment by ladyada** [comment]
nope
