### ISSUE TITLE
VEML6075 negative or low UV index

### ISSUE THREAD

**Issue by szerwi** [adafruit/Adafruit_VEML6075#9]
Hi,

I have two different VEML6075 modules:
First (let's call it purple):
![image](https://user-images.githubusercontent.com/19311511/121867989-c8f31500-cd00-11eb-8f3c-a1ce00c300e2.png)

Second (black):
![image](https://user-images.githubusercontent.com/19311511/121868045-d3adaa00-cd00-11eb-8d28-9d103a8c31c8.png)

The purple one is working ok. Indoors, when I put the LED light on it, it shows around 0.5 UV index. On the outside the values are close to other meteorological stations.
However, the black sensor is often showing negative values or the values are much lower than from the purple sensor. When I flash the LED light on it, the UV index is around -0.5 (negative value). Outside, in the direct sun it shows around 3.5, when at the same time the purple sensor shows 5.0.

Does it mean that the black sensor is damaged? Or is that a problem with the library / sketch? Both sensors were tested on exactly the same sketch.

- Arduino board:  ESP32 Dev Module

- Arduino IDE version (found in Arduino -> About Arduino menu):  2.0.0-beta7

- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too):

```
#include <Wire.h>
#include <Adafruit_VEML6075.h>

#define VEML6075_COEFFICIENT_A 0.001151
#define VEML6075_COEFFICIENT_B 0.001973

Adafruit_VEML6075 veml6075 = Adafruit_VEML6075();

uint32_t readTime = 0;

void setup() {
  Serial.begin(115200);

  Wire.begin(4, 16);

  veml6075.begin();
  veml6075.setIntegrationTime(VEML6075_100MS);
  veml6075.setHighDynamic(false);
  veml6075.setForcedMode(false);
}

void loop() {
  if(millis() - readTime >= 5000) {
    veml6075.setCoefficients(2.22, 1.33, 2.95, 1.74, 0.001461, 0.002591);
    Serial.print("UVA: "); Serial.println(veml6075.readUVA());
    Serial.print("UVB: "); Serial.println(veml6075.readUVB());
    Serial.print("UV (default): "); Serial.println(veml6075.readUVI());
    veml6075.setCoefficients(2.22, 1.33, 2.95, 1.74, VEML6075_COEFFICIENT_A, VEML6075_COEFFICIENT_B);
    Serial.print("UV (mine): "); Serial.println(veml6075.readUVI());
    readTime = millis();
  }
}

```

**Comment by ladyada** [comment]
hi please contact the places you purchased the hardware from for tech support - we dont own those boards so cannot help :)
